# This file is autogenerated from update.sh in the same directory.
{
  gwenhywfar.version = "5.1.3";
  gwenhywfar.sha256 = "0xjr9d94y46h7pfdhz5ygn01pmlm66rhiybr520h13nvjh4zid0r";
  gwenhywfar.releaseId = "242";
  libchipcard.version = "5.1.5rc2";
  libchipcard.sha256 = "0ylvqydiy56qy7dbzq1mhhrlgzzb6d9n1qncq0vb5v7p77zgilij";
  libchipcard.releaseId = "229";
  aqbanking.version = "6.0.2";
  aqbanking.sha256 = "0n41n3yki1wmax4i9wi485g8zqb43z1adywcixzfq9gbdjhz05hx";
  aqbanking.releaseId = "243";
}
