# This file is autogenerated from update.sh in the same directory.
{
  gwenhywfar.version = "5.1.3";
  gwenhywfar.sha256 = "0dcsqz013fgqiwg4dl51jw25fjvwn9fs7b56kfn90h47b9gfakng";
  gwenhywfar.releaseId = "242";
  libchipcard.version = "5.1.5rc2";
  libchipcard.sha256 = "1xd7kwwhgk9ania1wjr13vwx8cg3b0nhnd6xay8gnlfxzx9z7lid";
  libchipcard.releaseId = "229";
  aqbanking.version = "6.0.1";
  aqbanking.sha256 = "1rh2rzj1mrxj36bxgwd67wc4d6z8d5vd7syf8qfims1zq072ri8x";
  aqbanking.releaseId = "238";
}
